### ISSUE TITLE
Error messages from `validate_records` aren't being displayed properly

### ISSUE THREAD

**Issue by jfi** [Shopify/record_store#219]
I've encountered an issue whereby running `record-store validate_records` doesn't properly output the error message.

Zone record:

```yml
    - type: TXT
      fqdn: google._domainkey.example.org.
      ttl: 3600
      txtdata: v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoTJgmEXwFH5Ohp6BF7DmYmeNzJhIgmJ5wxR2b4IFPxCTryjcGUzjqz25tSiK7GCA4VlHO8Hx+nD/myUquUGYR8T3v9SINVhWYsz4dx/V4Ov1mPzuyxjjmDm9zfw8hLp+EAx3sZw32drmWdJG1X/XIybk+2P99g1UEx0UPvu86BUVWtdz963/GblNsRHcbcbOCRvqYiI3PN4wVNB3oE6FNZ66z7WfOTu7w0NnNlcR3/6g5C3ouGup8ARD7/8b3ugOdLk+tuDSAEY+7OvVvEksiWll2eiaz36Z3JIQ51Cs3zcVbRt4dZDvO67s1TSYLvQK0igZf1JnXLI5mGwtz2wDpQIDAQAB
```

The semicolons in `txtdata` above are unescaped, which should (and does) fail validation on `Record::TXT#escaped_semicolons`. However, it outputs the following error message:

```
example.org definition is not valid:
 - Records invalid record: [TXTRecord] google._domainkey.example.org. 3600 IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoTJgmEXwFH5Ohp6BF7DmYmeNzJhIgmJ5wxR2b4IFPxCTryjcGUzjqz25tSiK7GCA4VlHO8Hx+nD/myUquUGYR8T3v9SINVhWYsz4dx/V4Ov1mPzuyxjjmDm9zfw8hLp+EAx3sZw32drmWdJG1X/XIybk+2P99g1UEx0UPvu86BUVWtdz963/GblNsRHcbcbOCRvqYiI3PN4wVNB3oE6FNZ66z7WfOTu7w0NnNlcR3/6g5C3ouGup8ARD7/8b3ugOdLk+tuDSAEY+7OvVvEksiWll2eiaz36Z3JIQ51Cs3zcVbRt4dZDvO67s1TSYLvQK0igZf1JnXLI5mGwtz2wDpQIDAQAB"
  Invalid records
    [TXTRecord] google._domainkey.example.org. 3600 IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoTJgmEXwFH5Ohp6BF7DmYmeNzJhIgmJ5wxR2b4IFPxCTryjcGUzjqz25tSiK7GCA4VlHO8Hx+nD/myUquUGYR8T3v9SINVhWYsz4dx/V4Ov1mPzuyxjjmDm9zfw8hLp+EAx3sZw32drmWdJG1X/XIybk+2P99g1UEx0UPvu86BUVWtdz963/GblNsRHcbcbOCRvqYiI3PN4wVNB3oE6FNZ66z7WfOTu7w0NnNlcR3/6g5C3ouGup8ARD7/8b3ugOdLk+tuDSAEY+7OvVvEksiWll2eiaz36Z3JIQ51Cs3zcVbRt4dZDvO67s1TSYLvQK0igZf1JnXLI5mGwtz2wDpQIDAQAB"
      --- #<ActiveModel::Error:0x000000013cab3618>: 
```

I haven't got time for a full PR at the moment (to look at what the issue is), but for now I'm using this as a temporary fix in `lib/record_store/cli.rb`:

```ruby
        invalid_records.each do |record|
          puts "    #{record}"
          record.errors.each do |field, msg|
            if field.is_a?(ActiveModel::Error)
              puts "      - #{field.full_message}"
            else
              puts "      - #{field}: #{msg}"
            end
          end
        end
```

I then get the actual error message in the output:

```
    [TXTRecord] google._domainkey.example.org. 3600 IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoTJgmEXwFH5Ohp6BF7DmYmeNzJhIgmJ5wxR2b4IFPxCTryjcGUzjqz25tSiK7GCA4VlHO8Hx+nD/myUquUGYR8T3v9SINVhWYsz4dx/V4Ov1mPzuyxjjmDm9zfw8hLp+EAx3sZw32drmWdJG1X/XIybk+2P99g1UEx0UPvu86BUVWtdz963/GblNsRHcbcbOCRvqYiI3PN4wVNB3oE6FNZ66z7WfOTu7w0NnNlcR3/6g5C3ouGup8ARD7/8b3ugOdLk+tuDSAEY+7OvVvEksiWll2eiaz36Z3JIQ51Cs3zcVbRt4dZDvO67s1TSYLvQK0igZf1JnXLI5mGwtz2wDpQIDAQAB"
      - Txtdata has unescaped semicolons (See RFC 1035).
```
