### ISSUE TITLE
Adding PTR records fails

### ISSUE THREAD

**Issue by jfi** [Shopify/record_store#222]
If my reading is correct (having spent half the day trying to figure out how PTR records work 😭), this should be a valid way to define a PTR record in record_store:

```yml
    - type: PTR
      fqdn: 121.121.121.in-addr.arpa.
      ttl: 3600
      ptrdname: example.org.
```

This raises the following error:

```
lib/record_store/zone.rb:209:in `block in validate_records': #<RecordStore::Record::PTR:0x000000012f216008 @fqdn="121.121.121.in-addr.arpa.", @ttl=3600, @id=nil, @ptrdname="example.org."> (RuntimeError)

      - Fqdn is invalid
      - Fqdn PTR records may only exist in the in-addr.arpa zone
````

I've made the following change to `Zone#validate_records` ~L208 which seems to fix this:

```ruby
        unless record.fqdn.end_with?(name) || (record.type == "PTR" && record.fqdn.end_with?("in-addr.arpa."))
```
