### ISSUE TITLE
TXT record quoting treated inconsistently across providers

### ISSUE THREAD

**Issue by sbfaulkner** [Shopify/record_store#58]
quoting of TXT records is not being applied consistently across all providers

1. (unquoted) text without whitespace appears to be applied correctly across all providers
2. quoted text appears to be applied correctly across all providers
3. (unquoted) text with whitespace is not applied correctly on GoogleCloudDNS *BUG*
4. diff incorrectly detects a difference for unquoted text on GoogleCloudDNS *BUG*
5. diff incorrectly detects a difference for quoted text on DynECT *BUG*

given the following TXT record definitions in yml...

``` yaml
  - type: TXT
    fqdn: txt.shopify.test.
    ttl: 30
    txtdata: text

  - type: TXT
    fqdn: txt.shopify.test.
    ttl: 30
    txtdata: "text with whitespace"

  - type: TXT
    fqdn: txt.shopify.test.
    ttl: 30
    txtdata: '"quoted text with whitespace"'
```

after applying in all three providers (DNSimple, DynECT, and GoogleCloudDNS), `dig` shows the following records...

```
$ dig +short TXT txt.shopify.test @ns1.dnsimple.com
"quoted text with whitespace"
"text"
"text with whitespace"

$ dig +short TXT txt.shopify.test @ns1.p19.dynect.net
"quoted text with whitespace"
"text"
"text with whitespace"

$ dig +short TXT txt.shopify.test @ns-cloud-a4.googledomains.com
"text"
"text" "with" "whitespace"
"quoted text with whitespace"
```

and `record-store diff` shows...

```
$ bin/record-store diff
Diffing 2 zones
.
Zone: shopify.test
--------------------
Provider: DynECT
Update:
 - [TXTRecord] txt.shopify.test. 30 IN TXT ""quoted text with whitespace""
--------------------
Provider: GoogleCloudDNS
Update:
 - [TXTRecord] txt.shopify.test. 30 IN TXT "text with whitespace"
 - [TXTRecord] txt.shopify.test. 30 IN TXT "text"
====================
```
